language: objective-c

script:
  - set -o pipefail
  - xcodebuild clean build -project MaskDrawing.xcodeproj -scheme MaskDrawing -sdk iphonesimulator -configuration Debug
  - xcodebuild clean build test -project MaskDrawing.xcodeproj - scheme MaskDrawingTests -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - bash <(curl -s https://codecov.io/bash)
